### ISSUE TITLE
node_modules/react-native-live-audio-fft/index.d.ts is not a module.ts

### ISSUE THREAD

**Issue by jlounds** [flyskywhy/react-native-live-audio-fft#1]
Hello - this sounds exactly like what I am looking for! When I try to follow the example in the Readme, the following line gives an error "File '/Users/myusername/apps/myappname/node_modules/react-native-live-audio-fft/index.d.ts' is not a module.ts(2306)"

import LiveAudioStream, {
  PowerLevel,
  NativeRecordReceivePCM,
  FrequencyHistogramView,
} from 'react-native-live-audio-fft';

I am pretty new to RN, and very new to TS, so I am not sure if it is something I am doing wrong, or a incompatibility with the latest version of RN? (0.72.7)

Thank you!

**Comment by flyskywhy** [comment]
How about try my https://github.com/flyskywhy/GCanvasRNExamples which is not using ts first?
