### ISSUE TITLE
dependency for audio fft , g canvas for ios is not working properly the errors i listed in description.

### ISSUE THREAD

**Issue by ahmedIcots** [flyskywhy/react-native-live-audio-fft#2]
1) F/Users/ventura/Desktop/reactNative/folder/passages/ios/Pods/GCanvas'
duplicate symbol '_HandleInputBuffer' in:
    /Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/RNAudioPcmStream/libRNAudioPcmStream.a(RNLiveAudioStream.o)

2)warning: no rule to process file '/Users/ventura/Desktop/reactNative/folder/passages/node_modules/@flyskywhy/react-native-gcanvas/core/src/gcanvas/shaders/shadow.glsl' of type 'text' for architecture 'x86_64' (in target 'GCanvas' from project 'Pods')
warning: no rule to process file 

3)    /Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/RNAudioRecord/libRNAudioRecord.a(RNAudioRecord.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

4) The following build commands failed:
	Ld /Users/ventura/Library/Developer/Xcode/DerivedData/passages-fvlgnkgwuqzcpqdcjgewfvbpcvob/Build/Products/Debug-iphonesimulator/passages.app/passages normal (in target 'passages' from project 'passages')
(1 failure)
]

**Comment by hieuminh65** [comment]
I have the same error when build with this library, did you fix it

**Comment by ahmedIcots** [comment]
> I have the same error when build with this library, did you fix it

not yet. no answer from the package developer. 
might needed to highlight that issue to g canvas library

**Comment by ahmedIcots** [comment]
> I have the same error when build with this library, did you fix it

the package works fine for ios @flyskywhy tested it

**Comment by flyskywhy** [comment]
duplicated with https://github.com/flyskywhy/react-native-gcanvas/issues/75
